### ISSUE TITLE
Ilegal move error

### ISSUE THREAD

**Issue by dsaito** [pioz/chess#11]
Dear pioz,

Thank you so much for providing such a great chess library to the Ruby community. Upon testing exception handling, I believe I found a small bug, and hope you can enlighten me in this regard. When an invalid move is entered during the early stages of the game in the format "d2d4q", my script throws an error message accordingly: "Illegal Move". However, the game object still accepts this string (it can be accessed with g.moves), and that causes some downstream errors. It actually considers the move a valid one, discarding only the piece promotion character (d2d4). Also, when a move is entered in the format "e4" or "2e4", the game object accepts them as legal, but the system still throws the Illegal Move exception. Any help would be greatly appreciated. Thank you and keep up the excellent work!

**Comment by pioz** [comment]
For the first problem: the ruby move method call one of the three `move` C methods (http://blog.pioz.it/chess/classes/Chess/CGame.html#method-i-move): the promotion parameter will be ignored if no promotion occurred.

For the second problem: "2e4" is considered a valid move because 2 is a disambiguating rank square.

Permit the promotion character and the disambiguating characters only when required is an inefficient waste of calculation time of the CPU.

What do you think about this?

**Comment by dsaito** [comment]
Thank you for the prompt response. I think I understand most of your statements. The disambiguity entries can be easily dealt with in my script. However, validation of the moves with promotion characters seems harder to implement. I believe that, to keep consistency, if the game object retains the move (even if the promotion character is disconsidered), the Illegal move error should not be raised... I'm still trying to find a way to get around this!

**Comment by pioz** [comment]
I've see that Gnuchess and other programs return an illegal move if you pass a promotion or disambiguating when it is not needed. So I think it's right to do the same with this library. Hope in the next few days fix this.
